# Generated by Django 5.0 on 2023-12-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratChat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.AddField(
            model_name='ratroom',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
