# Generated by Django 4.0 on 2023-12-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ratChat', '0002_delete_mensaje_ratroom_slug_alter_ratroom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ratChat.ratroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='auth.user')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
