# Generated by Django 4.0 on 2023-12-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratChat', '0003_ratmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratroom',
            name='rat',
            field=models.ImageField(default='static/img/ratonEscondido.jpg', upload_to='static/img'),
        ),
    ]
