# Generated by Django 4.0 on 2023-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratChat', '0004_ratroom_rat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat', models.ImageField(upload_to='static/img/sticker')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
